
-- Update existing services with category and checklist_template
UPDATE public.services SET category = 'MV-reiniging', name = 'Basis reiniging', checklist_template = '[{"label":"Reinigen ventilatiekanalen","checked":false},{"label":"Ventilatieroosters reinigen","checked":false},{"label":"Reinigen ventielen","checked":false},{"label":"Ventilatieadvies","checked":false},{"label":"Voor-foto''s gemaakt","checked":false},{"label":"Na-foto''s gemaakt","checked":false}]'::jsonb WHERE id = '1dd3163e-7fd6-41da-ba35-3a23bc0b8af0';

UPDATE public.services SET category = 'MV-reiniging', checklist_template = '[{"label":"Inspectie ventilatiebox","checked":false},{"label":"Reinigen ventilatiebox","checked":false},{"label":"Reinigen ventilatiekanalen","checked":false},{"label":"Ventilatieroosters reinigen","checked":false},{"label":"Inregelen ventilatie systeem","checked":false},{"label":"Reinigen ventielen","checked":false},{"label":"Ventilatieadvies","checked":false},{"label":"Voor-foto''s gemaakt","checked":false},{"label":"Na-foto''s gemaakt","checked":false}]'::jsonb WHERE id = 'b0d5d372-7113-41ff-a4ee-627f89dd1129';

UPDATE public.services SET category = 'WTW onderhoud', name = 'Klein onderhoud', checklist_template = '[{"label":"Inspectie WTW unit","checked":false},{"label":"Reinigen WTW unit","checked":false},{"label":"Onderhoud WTW unit","checked":false},{"label":"Reinigen ventilatiekanalen","checked":false},{"label":"Onderhoud toevoer & afvoermotor","checked":false},{"label":"Ventilatieadvies","checked":false},{"label":"Voor-foto''s gemaakt","checked":false},{"label":"Na-foto''s gemaakt","checked":false}]'::jsonb WHERE id = '963d4715-6d92-4679-9958-0aeca69a1472';

-- Insert new services
INSERT INTO public.services (name, price, category, checklist_template, color) VALUES
('Zehnder ComfoFan Silent - Euro', 565, 'MV-box vervangen', '[{"label":"MV-box vervangen","checked":false},{"label":"Aansluiting gecontroleerd","checked":false},{"label":"Systeem getest","checked":false},{"label":"Voor-foto''s gemaakt","checked":false},{"label":"Na-foto''s gemaakt","checked":false}]'::jsonb, '#6366f1'),
('Zehnder ComfoFan Silent - Perilex', 565, 'MV-box vervangen', '[{"label":"MV-box vervangen","checked":false},{"label":"Aansluiting gecontroleerd","checked":false},{"label":"Systeem getest","checked":false},{"label":"Voor-foto''s gemaakt","checked":false},{"label":"Na-foto''s gemaakt","checked":false}]'::jsonb, '#6366f1'),
('Duco DucoBox Silent - Euro', 535, 'MV-box vervangen', '[{"label":"MV-box vervangen","checked":false},{"label":"Aansluiting gecontroleerd","checked":false},{"label":"Systeem getest","checked":false},{"label":"Voor-foto''s gemaakt","checked":false},{"label":"Na-foto''s gemaakt","checked":false}]'::jsonb, '#6366f1'),
('Duco DucoBox Silent - Perilex', 535, 'MV-box vervangen', '[{"label":"MV-box vervangen","checked":false},{"label":"Aansluiting gecontroleerd","checked":false},{"label":"Systeem getest","checked":false},{"label":"Voor-foto''s gemaakt","checked":false},{"label":"Na-foto''s gemaakt","checked":false}]'::jsonb, '#6366f1'),
('Groot onderhoud', 275, 'WTW onderhoud', '[{"label":"Inspectie WTW unit","checked":false},{"label":"Reinigen WTW unit","checked":false},{"label":"Filters vervangen","checked":false},{"label":"Onderhoud WTW unit","checked":false},{"label":"Reinigen ventilatiekanalen","checked":false},{"label":"Inregelen ventilatie systeem","checked":false},{"label":"Onderhoud warmtewisselaar","checked":false},{"label":"Inspectie van toevoerkanalen","checked":false},{"label":"Onderhoud toevoer & afvoermotor","checked":false},{"label":"Ventilatieadvies","checked":false},{"label":"Meetrapport opgesteld","checked":false},{"label":"Voor-foto''s gemaakt","checked":false},{"label":"Na-foto''s gemaakt","checked":false}]'::jsonb, '#f59e0b'),
('Itho Daalderop WTW', 1995, 'WTW-unit vervangen', '[{"label":"WTW-unit vervangen","checked":false},{"label":"Aansluiting gecontroleerd","checked":false},{"label":"Systeem getest","checked":false},{"label":"Inregelen ventilatie systeem","checked":false},{"label":"Voor-foto''s gemaakt","checked":false},{"label":"Na-foto''s gemaakt","checked":false}]'::jsonb, '#ef4444'),
('Zehnder ComfoAir Q350', 3448.86, 'WTW-unit vervangen', '[{"label":"WTW-unit vervangen","checked":false},{"label":"Aansluiting gecontroleerd","checked":false},{"label":"Systeem getest","checked":false},{"label":"Inregelen ventilatie systeem","checked":false},{"label":"Voor-foto''s gemaakt","checked":false},{"label":"Na-foto''s gemaakt","checked":false}]'::jsonb, '#ef4444');
