// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sigzpqwnavfxtvbyqvzj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNpZ3pwcXduYXZmeHR2YnlxdnpqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzIxMjM5MjUsImV4cCI6MjA4NzY5OTkyNX0.viejbTLs6i3GD6gETBNNoUTAOugkKQyY2EYVvOFa-3k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});